name: jjkhjj
description: ''
version: '11'
author: suryansh@adobe.com
language: python
buildSystem: wheel
pipelines:
  pipelines/sur:
    name: sur
    description: ''
    author: suryansh@adobe.com
    mode: batch
    language: python
    createdAt: '2023-02-19 19:58:39'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
