name: jjkhjj
description: ''
version: 0.0.1-SNAPSHOT
author: suryansh@adobe.com
language: python
buildSystem: wheel
pipelines:
  pipelines/sur:
    name: sur
    description: ''
    author: suryansh@adobe.com
    mode: batch
    language: python
    createdAt: '2023-02-19 19:58:39'
    datasets:
      inputs: []
      outputs: []
    dependencies: {}
datasets: {}
templates: {}
jobs:
  jobs/ankita:
    name: ankita
    description: ''
    fabricUID: 4
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1/1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2023-02-19 21:30:35'
    author: ankitagu@adobe.com
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
